server:
  port: 8033


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zz_my?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin

  mybatis:
    config-locations: classpath*:mybatis-config.xml
    mapper-locations: classpath*:mapper/*.xml

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms


